# Generated by Django 3.1.1 on 2020-09-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200905_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='zip',
        ),
        migrations.AddField(
            model_name='todo',
            name='city',
            field=models.CharField(default='Portland', max_length=200),
        ),
    ]
