# Generated by Django 3.1.1 on 2020-09-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20200905_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='temp',
            new_name='required_temp',
        ),
        migrations.AddField(
            model_name='todo',
            name='current_temp',
            field=models.IntegerField(default=70),
        ),
    ]
