# Generated by Django 3.1.1 on 2020-09-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20200905_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='current_temp',
        ),
        migrations.AddField(
            model_name='todo',
            name='zip',
            field=models.IntegerField(default=97217),
        ),
    ]
