# Generated by Django 3.1.1 on 2020-09-06 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20200906_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='city',
        ),
    ]
