# Generated by Django 3.1.1 on 2020-09-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_remove_todo_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='city',
            field=models.CharField(default='x', max_length=200),
        ),
        migrations.AddField(
            model_name='todo',
            name='current_temp',
            field=models.IntegerField(default=-1),
        ),
    ]
